contractAddress: "0xC1afEbE677baDb71FC760e61479227e43B422E48"
agents:
  - username: "0xargumint"
    address: "0x518EbE66287140e9378b9F8D00797291A8dfc2bc"
  - username: "0xagreemint"
    address: "0x53Dd4b9627eb9691D62B90dDD987a8c8DFC99a12"
  - username: "hindsight2157"
    address: "0xf9c4db01387701c7fA19B5bEbd6716b4F9E66aBA"